api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'children', views.ChildViewSet)
router.register(r'changes', views.DiaperChangeViewSet)
router.register(r'feedings', views.FeedingViewSet)
router.register(r'notes', views.NoteViewSet)
router.register(r'sleep', views.SleepViewSet)
router.register(r'temperature', views.TemperatureViewSet)
router.register(r'timers', views.TimerViewSet)
router.register(r'tummy-times', views.TummyTimeViewSet)
router.register(r'weight', views.WeightViewSet)

app_name = 'api'

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/auth/', include(
        'rest_framework.urls',
        namespace='rest_framework'
    ))
]

core/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('children/', views.ChildList.as_view(), name='child-list'),
    path('children/add/', views.ChildAdd.as_view(), name='child-add'),
    path('children/<slug:slug>/', views.ChildDetail.as_view(), name='child'),
    path(
        'children/<slug:slug>/edit/',
        views.ChildUpdate.as_view(),
        name='child-update'
    ),
    path(
        'children/<slug:slug>/delete/',
        views.ChildDelete.as_view(),
        name='child-delete'
    ),

    path(
        'changes/',
        views.DiaperChangeList.as_view(),
        name='diaperchange-list'
    ),
    path(
        'changes/add/',
        views.DiaperChangeAdd.as_view(),
        name='diaperchange-add'
    ),
    path(
        'changes/<int:pk>/',
        views.DiaperChangeUpdate.as_view(),
        name='diaperchange-update'
    ),
    path(
        'changes/<int:pk>/delete/',
        views.DiaperChangeDelete.as_view(),
        name='diaperchange-delete'
    ),

    path('feedings/', views.FeedingList.as_view(), name='feeding-list'),
    path('feedings/add/', views.FeedingAdd.as_view(), name='feeding-add'),
    path(
        'feedings/<int:pk>/',
        views.FeedingUpdate.as_view(),
        name='feeding-update'
    ),
    path(
        'feedings/<int:pk>/delete/',
        views.FeedingDelete.as_view(),
        name='feeding-delete'
    ),

    path('notes/', views.NoteList.as_view(), name='note-list'),
    path('notes/add/', views.NoteAdd.as_view(), name='note-add'),
    path('notes/<int:pk>/', views.NoteUpdate.as_view(), name='note-update'),
    path(
        'notes/<int:pk>/delete/',
        views.NoteDelete.as_view(),
        name='note-delete'
    ),

    path('sleep/', views.SleepList.as_view(), name='sleep-list'),
    path('sleep/add/', views.SleepAdd.as_view(), name='sleep-add'),
    path('sleep/<int:pk>/', views.SleepUpdate.as_view(), name='sleep-update'),
    path(
        'sleep/<int:pk>/delete/',
        views.SleepDelete.as_view(),
        name='sleep-delete'
    ),

    path(
        'temperature/',
        views.TemperatureList.as_view(),
        name='temperature-list'
    ),
    path(
        'temperature/add/',
        views.TemperatureAdd.as_view(),
        name='temperature-add'
    ),
    path(
        'temperature/<int:pk>/',
        views.TemperatureUpdate.as_view(),
        name='temperature-update'
    ),
    path(
        'temperature/<int:pk>/delete/',
        views.TemperatureDelete.as_view(),
        name='temperature-delete'
    ),

    path('timers/', views.TimerList.as_view(), name='timer-list'),
    path('timers/add/', views.TimerAdd.as_view(), name='timer-add'),
    path(
        'timers/add/quick/',
        views.TimerAddQuick.as_view(),
        name='timer-add-quick'
    ),
    path('timers/<int:pk>/', views.TimerDetail.as_view(), name='timer-detail'),
    path(
        'timers/<int:pk>/edit/',
        views.TimerUpdate.as_view(),
        name='timer-update'
    ),
    path(
        'timers/<int:pk>/delete/',
        views.TimerDelete.as_view(),
        name='timer-delete'
    ),
    path(
        'timers/<int:pk>/stop/',
        views.TimerStop.as_view(),
        name='timer-stop'
    ),
    path(
        'timers/<int:pk>/restart/',
        views.TimerRestart.as_view(),
        name='timer-restart'
    ),
    path(
        'timers/delete-inactive/',
        views.TimerDeleteInactive.as_view(),
        name='timer-delete-inactive'
    ),

    path('tummy-time/', views.TummyTimeList.as_view(), name='tummytime-list'),
    path(
        'tummy-time/add/',
        views.TummyTimeAdd.as_view(),
        name='tummytime-add'
    ),
    path(
        'tummy-time/<int:pk>/',
        views.TummyTimeUpdate.as_view(),
        name='tummytime-update'
    ),
    path(
        'tummy-time/<int:pk>/delete/',
        views.TummyTimeDelete.as_view(),
        name='tummytime-delete'
    ),

    path('weight/', views.WeightList.as_view(), name='weight-list'),
    path('weight/add/', views.WeightAdd.as_view(), name='weight-add'),
    path(
        'weight/<int:pk>/',
        views.WeightUpdate.as_view(),
        name='weight-update'
    ),
    path(
        'weight/<int:pk>/delete/',
        views.WeightDelete.as_view(),
        name='weight-delete'
    ),
]

dashboard/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path(
        'children/<slug:slug>/dashboard/',
        views.ChildDashboard.as_view(),
        name='dashboard-child'
    ),
]

reports/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'reports'

urlpatterns = [
    path(
        'children/<slug:slug>/reports/changes/amounts/',
        views.DiaperChangeAmounts.as_view(),
        name='report-diaperchange-amounts-child'
    ),
    path(
        'children/<slug:slug>/reports/changes/lifetimes/',
        views.DiaperChangeLifetimesChildReport.as_view(),
        name='report-diaperchange-lifetimes-child'
    ),
    path(
        'children/<slug:slug>/reports/changes/types/',
        views.DiaperChangeTypesChildReport.as_view(),
        name='report-diaperchange-types-child'
    ),
    path(
        'children/<slug:slug>/reports/feeding/amounts/',
        views.FeedingAmountsChildReport.as_view(),
        name='report-feeding-amounts-child'
    ),
    path(
        'children/<slug:slug>/reports/feeding/duration/',
        views.FeedingDurationChildReport.as_view(),
        name='report-feeding-duration-child'
    ),
    path(
        'children/<slug:slug>/reports/sleep/pattern/',
        views.SleepPatternChildReport.as_view(),
        name='report-sleep-pattern-child'
    ),
    path(
        'children/<slug:slug>/reports/sleep/totals/',
        views.SleepTotalsChildReport.as_view(),
        name='report-sleep-totals-child'
    ),
    path(
        'children/<slug:slug>/reports/weight/weight/',
        views.WeightWeightChildReport.as_view(),
        name='report-weight-weight-child'
    ),
]

core/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _


def validate_date(date, field_name):
    """
    Confirm that a date is not in the future.
    :param date: a timezone aware date instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if date and date > timezone.localdate():
        raise ValidationError(
            {field_name: _('Date can not be in the future.')},
            code='date_invalid')


def validate_duration(model, max_duration=timedelta(hours=24)):
    """
    Basic sanity checks for models with a duration
    :param model: a model instance with 'start' and 'end' attributes
    :param max_duration: maximum allowed duration between start and end time
    :return:
    """
    if model.start and model.end:
        if model.start > model.end:
            raise ValidationError(
                _('Start time must come before end time.'),
                code='end_before_start')
        if model.end - model.start > max_duration:
            raise ValidationError(_('Duration too long.'), code='max_duration')


def validate_unique_period(queryset, model):
    """
    Confirm that model's start and end date do not intersect with other
    instances.
    :param queryset: a queryset of instances to check against.
    :param model: a model instance with 'start' and 'end' attributes
    :return:
    """
    if model.id:
        queryset = queryset.exclude(id=model.id)
    if model.start and model.end:
        if queryset.filter(start__lte=model.end, end__gte=model.start):
            raise ValidationError(
                _('Another entry intersects the specified time period.'),
                code='period_intersection')


def validate_time(time, field_name):
    """
    Confirm that a time is not in the future.
    :param time: a timezone aware datetime instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if time and time > timezone.localtime():
        raise ValidationError(
            {field_name: _('Date/time can not be in the future.')},
            code='time_invalid')


class Child(models.Model):
    model_name = 'child'
    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last name'))
    birth_date = models.DateField(
        blank=False,
        null=False,
        verbose_name=_('Birth date')
    )
    slug = models.SlugField(
        editable=False,
        max_length=100,
        unique=True,
        verbose_name=_('Slug')
    )
    picture = models.ImageField(
        blank=True,
        null=True,
        upload_to='child/picture/',
        verbose_name=_('Picture')
    )

    objects = models.Manager()

    cache_key_count = 'core.child.count'

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['last_name', 'first_name']
        verbose_name = _('Child')
        verbose_name_plural = _('Children')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self)
        super(Child, self).save(*args, **kwargs)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def delete(self, using=None, keep_parents=False):
        super(Child, self).delete(using, keep_parents)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def name(self, reverse=False):
        if reverse:
            return '{}, {}'.format(self.last_name, self.first_name)

        return '{} {}'.format(self.first_name, self.last_name)

    @classmethod
    def count(cls):
        """ Get a (cached) count of total number of Child instances. """
        return cache.get_or_set(cls.cache_key_count, Child.objects.count, None)


class DiaperChange(models.Model):
    model_name = 'diaperchange'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='diaper_change',
        verbose_name=_('Child')
    )
    time = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Time')
    )
    wet = models.BooleanField(verbose_name=_('Wet'))
    solid = models.BooleanField(verbose_name=_('Solid'))
    color = models.CharField(
        blank=True,
        choices=[
            ('black', _('Black')),
            ('brown', _('Brown')),
            ('green', _('Green')),
            ('yellow', _('Yellow')),
        ],
        max_length=255,
        verbose_name=_('Color')
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_('Amount'))
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-time']
        verbose_name = _('Diaper Change')
        verbose_name_plural = _('Diaper Changes')

    def __str__(self):
        return str(_('Diaper Change'))

    def attributes(self):
        attributes = []
        if self.wet:
            attributes.append(self._meta.get_field('wet').verbose_name)
        if self.solid:
            attributes.append(self._meta.get_field('solid').verbose_name)
        if self.color:
            attributes.append(self.get_color_display())
        return attributes

    def clean(self):
        validate_time(self.time, 'time')

        # One or both of Wet and Solid is required.
        if not self.wet and not self.solid:
            raise ValidationError(
                _('Wet and/or solid is required.'), code='wet_or_solid')


class Feeding(models.Model):
    model_name = 'feeding'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='feeding',
        verbose_name=_('Child')
    )
    start = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Start time')
    )
    end = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('End time')
    )
    duration = models.DurationField(
        editable=False,
        null=True,
        verbose_name=_('Duration')
    )
    type = models.CharField(
        choices=[
            ('breast milk', _('Breast milk')),
            ('formula', _('Formula')),
            ('fortified breast milk', _('Fortified breast milk')),
        ],
        max_length=255,
        verbose_name=_('Type')
    )
    method = models.CharField(
        choices=[
            ('bottle', _('Bottle')),
            ('left breast', _('Left breast')),
            ('right breast', _('Right breast')),
            ('both breasts', _('Both breasts')),
        ],
        max_length=255,
        verbose_name=_('Method')
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_('Amount'))
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-start']
        verbose_name = _('Feeding')
        verbose_name_plural = _('Feedings')

    def __str__(self):
        return str(_('Feeding'))

    def save(self, *args, **kwargs):
        if self.start and self.end:
            self.duration = self.end - self.start
        super(Feeding, self).save(*args, **kwargs)

    def clean(self):
        validate_time(self.start, 'start')
        validate_time(self.end, 'end')
        validate_duration(self)
        validate_unique_period(Feeding.objects.filter(child=self.child), self)


class Note(models.Model):
    model_name = 'note'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='note',
        verbose_name=_('Child')
    )
    note = models.TextField(verbose_name=_('Note'))
    time = models.DateTimeField(auto_now=True, verbose_name=_('Time'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-time']
        verbose_name = _('Note')
        verbose_name_plural = _('Notes')

    def __str__(self):
        return str(_('Note'))


class NapsManager(models.Manager):
    def get_queryset(self):
        qs = super(NapsManager, self).get_queryset()
        return qs.filter(id__in=[obj.id for obj in qs if obj.nap])


class Sleep(models.Model):
    model_name = 'sleep'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='sleep',
        verbose_name=_('Child')
    )
    start = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Start time')
    )
    end = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('End time')
    )
    duration = models.DurationField(
        editable=False,
        null=True,
        verbose_name=_('Duration')
    )
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()
    naps = NapsManager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-start']
        verbose_name = _('Sleep')
        verbose_name_plural = _('Sleep')

    def __str__(self):
        return str(_('Sleep'))

    @property
    def nap(self):
        nap_start_min = timezone.datetime.strptime(
            settings.BABY_BUDDY['NAP_START_MIN'], '%H:%M').time()
        nap_start_max = timezone.datetime.strptime(
            settings.BABY_BUDDY['NAP_START_MAX'], '%H:%M').time()
        local_start_time = timezone.localtime(self.start).time()

dashboard/templates/dashboard/child.html
{% extends 'babybuddy/page.html' %}
{% load cards i18n %}

{% block title %}{% trans "Dashboard" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'core:child-list' %}">{% trans "Children" %}</a></li>
    <li class="breadcrumb-item font-weight-bold"><a href="{% url 'core:child' object.slug %}">{{ object }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "Dashboard" %}</li>
{% endblock %}

{% block content %}
    <div id="dashboard-child" class="card-columns">
        {% card_feeding_last object %}
        {% card_feeding_last_method object %}
        {% card_timer_list object %}
        {% card_statistics object %}
        {% card_sleep_last object %}
        {% card_sleep_day object %}
        {% card_sleep_naps_day object %}
        {% card_tummytime_day object %}
        {% card_diaperchange_last object %}
        {% card_diaperchange_types object %}
    </div>
{% endblock %}

{% block javascript %}
    {% if user.settings.dashboard_refresh_rate %}
        <script type="application/javascript">
            BabyBuddy.Dashboard.watch('dashboard-child', {{ user.settings.dashboard_refresh_rate_milliseconds }});
        </script>
    {% else %}
        <script type="application/javascript">
            BabyBuddy.Dashboard.watch('dashboard-child', false);
        </script>
    {% endif %}
{% endblock %}

dashboard/templates/dashboard/child_button_group.html
{% load i18n %}

<div class="child-actions btn-group btn-group-md center-block" role="group" aria-label="{% trans "Child actions" %}">

    {% if perms.core.view_child %}
        <a href="{% url 'dashboard:dashboard-child' object.slug %}" class="btn btn-success">
            <i class="icon icon-dashboard" aria-hidden="true"></i>
        </a>
    {% endif %}

    <div class="btn-group" role="group">
        <button id="reports-dropdown"
                class="btn btn-primary dropdown-toggle"
                type="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"><i class="icon icon-graph" aria-hidden="true"></i></button>
        <div class="dropdown-menu" aria-labelledby="reports-dropdown">
            <a class="dropdown-item" href="{% url 'reports:report-diaperchange-amounts-child' object.slug %}">{% trans "Diaper Change Amounts" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-diaperchange-types-child' object.slug %}">{% trans "Diaper Change Types" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-diaperchange-lifetimes-child' object.slug %}">{% trans "Diaper Lifetimes" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-feeding-amounts-child' object.slug %}">{% trans "Feeding Amounts" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-feeding-duration-child' object.slug %}">{% trans "Feeding Durations (Average)" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-sleep-pattern-child' object.slug %}">{% trans "Sleep Pattern" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-sleep-totals-child' object.slug %}">{% trans "Sleep Totals" %}</a>
            <a class="dropdown-item" href="{% url 'reports:report-weight-weight-child' object.slug %}">{% trans "Weight" %}</a>
        </div>
    </div>

    {% if perms.core.change_child %}
        <a class="btn btn-warning"
           href="{% url 'core:child-update' object.slug %}"
           role="button"><i class="icon icon-update" aria-hidden="true"></i></a>
    {% endif %}

    {% if perms.core.delete_child %}
        <a class="btn btn-danger"
           href="{% url 'core:child-delete' object.slug %}"
           role="button"><i class="icon icon-delete" aria-hidden="true"></i></a>
    {% endif %}

</div>

dashboard/templates/dashboard/dashboard.html
{% extends 'babybuddy/page.html' %}
{% load cards i18n static thumbnail %}

{% block title %}{% trans "Dashboard" %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item font-weight-bold">{% trans "Dashboard" %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            {% card_timer_list %}
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="row">
            {% for object in objects %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-2 mb-4">
                    <div class="card">
                        <a class="text-center" href="{% url 'core:child' object.slug %}">
                            {% if object.picture %}
                                {% thumbnail object.picture 300x300 upscale crop as thumb %}
                                <img src="{{ thumb.url }}" class="child-photo img-fluid" />
                            {% else %}
                                <img src="{% static 'babybuddy/img/core/child-placeholder.png' %}" class="child-photo img-fluid" />
                            {% endif %}
                        </a>
                        <div class="card-body text-center">
                            <h4 class="card-title">{{ object }}</h4>
                            <div class="card-text">
                                <p>
                                    {% trans "Born" %} <span class="text-secondary">{{ object.birth_date }}</span><br/>
                                    {% trans "Age" %} <span class="text-secondary">{{ object.birth_date|timesince }}</span>
                                </p>
                                {% include 'dashboard/child_button_group.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}