api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'children', views.ChildViewSet)
router.register(r'changes', views.DiaperChangeViewSet)
router.register(r'feedings', views.FeedingViewSet)
router.register(r'notes', views.NoteViewSet)
router.register(r'sleep', views.SleepViewSet)
router.register(r'temperature', views.TemperatureViewSet)
router.register(r'timers', views.TimerViewSet)
router.register(r'tummy-times', views.TummyTimeViewSet)
router.register(r'weight', views.WeightViewSet)

app_name = 'api'

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/auth/', include(
        'rest_framework.urls',
        namespace='rest_framework'
    ))
]

core/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('children/', views.ChildList.as_view(), name='child-list'),
    path('children/add/', views.ChildAdd.as_view(), name='child-add'),
    path('children/<slug:slug>/', views.ChildDetail.as_view(), name='child'),
    path(
        'children/<slug:slug>/edit/',
        views.ChildUpdate.as_view(),
        name='child-update'
    ),
    path(
        'children/<slug:slug>/delete/',
        views.ChildDelete.as_view(),
        name='child-delete'
    ),

    path(
        'changes/',
        views.DiaperChangeList.as_view(),
        name='diaperchange-list'
    ),
    path(
        'changes/add/',
        views.DiaperChangeAdd.as_view(),
        name='diaperchange-add'
    ),
    path(
        'changes/<int:pk>/',
        views.DiaperChangeUpdate.as_view(),
        name='diaperchange-update'
    ),
    path(
        'changes/<int:pk>/delete/',
        views.DiaperChangeDelete.as_view(),
        name='diaperchange-delete'
    ),

    path('feedings/', views.FeedingList.as_view(), name='feeding-list'),
    path('feedings/add/', views.FeedingAdd.as_view(), name='feeding-add'),
    path(
        'feedings/<int:pk>/',
        views.FeedingUpdate.as_view(),
        name='feeding-update'
    ),
    path(
        'feedings/<int:pk>/delete/',
        views.FeedingDelete.as_view(),
        name='feeding-delete'
    ),

    path('notes/', views.NoteList.as_view(), name='note-list'),
    path('notes/add/', views.NoteAdd.as_view(), name='note-add'),
    path('notes/<int:pk>/', views.NoteUpdate.as_view(), name='note-update'),
    path(
        'notes/<int:pk>/delete/',
        views.NoteDelete.as_view(),
        name='note-delete'
    ),

    path('sleep/', views.SleepList.as_view(), name='sleep-list'),
    path('sleep/add/', views.SleepAdd.as_view(), name='sleep-add'),
    path('sleep/<int:pk>/', views.SleepUpdate.as_view(), name='sleep-update'),
    path(
        'sleep/<int:pk>/delete/',
        views.SleepDelete.as_view(),
        name='sleep-delete'
    ),

    path(
        'temperature/',
        views.TemperatureList.as_view(),
        name='temperature-list'
    ),
    path(
        'temperature/add/',
        views.TemperatureAdd.as_view(),
        name='temperature-add'
    ),
    path(
        'temperature/<int:pk>/',
        views.TemperatureUpdate.as_view(),
        name='temperature-update'
    ),
    path(
        'temperature/<int:pk>/delete/',
        views.TemperatureDelete.as_view(),
        name='temperature-delete'
    ),

    path('timers/', views.TimerList.as_view(), name='timer-list'),
    path('timers/add/', views.TimerAdd.as_view(), name='timer-add'),
    path(
        'timers/add/quick/',
        views.TimerAddQuick.as_view(),
        name='timer-add-quick'
    ),
    path('timers/<int:pk>/', views.TimerDetail.as_view(), name='timer-detail'),
    path(
        'timers/<int:pk>/edit/',
        views.TimerUpdate.as_view(),
        name='timer-update'
    ),
    path(
        'timers/<int:pk>/delete/',
        views.TimerDelete.as_view(),
        name='timer-delete'
    ),
    path(
        'timers/<int:pk>/stop/',
        views.TimerStop.as_view(),
        name='timer-stop'
    ),
    path(
        'timers/<int:pk>/restart/',
        views.TimerRestart.as_view(),
        name='timer-restart'
    ),
    path(
        'timers/delete-inactive/',
        views.TimerDeleteInactive.as_view(),
        name='timer-delete-inactive'
    ),

    path('tummy-time/', views.TummyTimeList.as_view(), name='tummytime-list'),
    path(
        'tummy-time/add/',
        views.TummyTimeAdd.as_view(),
        name='tummytime-add'
    ),
    path(
        'tummy-time/<int:pk>/',
        views.TummyTimeUpdate.as_view(),
        name='tummytime-update'
    ),
    path(
        'tummy-time/<int:pk>/delete/',
        views.TummyTimeDelete.as_view(),
        name='tummytime-delete'
    ),

    path('weight/', views.WeightList.as_view(), name='weight-list'),
    path('weight/add/', views.WeightAdd.as_view(), name='weight-add'),
    path(
        'weight/<int:pk>/',
        views.WeightUpdate.as_view(),
        name='weight-update'
    ),
    path(
        'weight/<int:pk>/delete/',
        views.WeightDelete.as_view(),
        name='weight-delete'
    ),
]

dashboard/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path(
        'children/<slug:slug>/dashboard/',
        views.ChildDashboard.as_view(),
        name='dashboard-child'
    ),
]

core/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _


def validate_date(date, field_name):
    """
    Confirm that a date is not in the future.
    :param date: a timezone aware date instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if date and date > timezone.localdate():
        raise ValidationError(
            {field_name: _('Date can not be in the future.')},
            code='date_invalid')


def validate_duration(model, max_duration=timedelta(hours=24)):
    """
    Basic sanity checks for models with a duration
    :param model: a model instance with 'start' and 'end' attributes
    :param max_duration: maximum allowed duration between start and end time
    :return:
    """
    if model.start and model.end:
        if model.start > model.end:
            raise ValidationError(
                _('Start time must come before end time.'),
                code='end_before_start')
        if model.end - model.start > max_duration:
            raise ValidationError(_('Duration too long.'), code='max_duration')


def validate_unique_period(queryset, model):
    """
    Confirm that model's start and end date do not intersect with other
    instances.
    :param queryset: a queryset of instances to check against.
    :param model: a model instance with 'start' and 'end' attributes
    :return:
    """
    if model.id:
        queryset = queryset.exclude(id=model.id)
    if model.start and model.end:
        if queryset.filter(start__lte=model.end, end__gte=model.start):
            raise ValidationError(
                _('Another entry intersects the specified time period.'),
                code='period_intersection')


def validate_time(time, field_name):
    """
    Confirm that a time is not in the future.
    :param time: a timezone aware datetime instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if time and time > timezone.localtime():
        raise ValidationError(
            {field_name: _('Date/time can not be in the future.')},
            code='time_invalid')


class Child(models.Model):
    model_name = 'child'
    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last name'))
    birth_date = models.DateField(
        blank=False,
        null=False,
        verbose_name=_('Birth date')
    )
    slug = models.SlugField(
        editable=False,
        max_length=100,
        unique=True,
        verbose_name=_('Slug')
    )
    picture = models.ImageField(
        blank=True,
        null=True,
        upload_to='child/picture/',
        verbose_name=_('Picture')
    )

    objects = models.Manager()

    cache_key_count = 'core.child.count'

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['last_name', 'first_name']
        verbose_name = _('Child')
        verbose_name_plural = _('Children')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self)
        super(Child, self).save(*args, **kwargs)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def delete(self, using=None, keep_parents=False):
        super(Child, self).delete(using, keep_parents)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def name(self, reverse=False):
        if reverse:
            return '{}, {}'.format(self.last_name, self.first_name)

        return '{} {}'.format(self.first_name, self.last_name)

    @classmethod
    def count(cls):
        """ Get a (cached) count of total number of Child instances. """
        return cache.get_or_set(cls.cache_key_count, Child.objects.count, None)


class DiaperChange(models.Model):
    model_name = 'diaperchange'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='diaper_change',
        verbose_name=_('Child')
    )
    time = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Time')
    )
    wet = models.BooleanField(verbose_name=_('Wet'))
    solid = models.BooleanField(verbose_name=_('Solid'))
    color = models.CharField(
        blank=True,
        choices=[
            ('black', _('Black')),
            ('brown', _('Brown')),
            ('green', _('Green')),
            ('yellow', _('Yellow')),
        ],
        max_length=255,
        verbose_name=_('Color')
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_('Amount'))
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-time']
        verbose_name = _('Diaper Change')
        verbose_name_plural = _('Diaper Changes')

    def __str__(self):
        return str(_('Diaper Change'))

    def attributes(self):
        attributes = []
        if self.wet:
            attributes.append(self._meta.get_field('wet').verbose_name)
        if self.solid:
            attributes.append(self._meta.get_field('solid').verbose_name)
        if self.color:
            attributes.append(self.get_color_display())
        return attributes

    def clean(self):
        validate_time(self.time, 'time')

        # One or both of Wet and Solid is required.
        if not self.wet and not self.solid:
            raise ValidationError(
                _('Wet and/or solid is required.'), code='wet_or_solid')


class Feeding(models.Model):
    model_name = 'feeding'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='feeding',
        verbose_name=_('Child')
    )
    start = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Start time')
    )
    end = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('End time')
    )
    duration = models.DurationField(
        editable=False,
        null=True,
        verbose_name=_('Duration')
    )
    type = models.CharField(
        choices=[
            ('breast milk', _('Breast milk')),
            ('formula', _('Formula')),
            ('fortified breast milk', _('Fortified breast milk')),
        ],
        max_length=255,
        verbose_name=_('Type')
    )
    method = models.CharField(
        choices=[
            ('bottle', _('Bottle')),
            ('left breast', _('Left breast')),
            ('right breast', _('Right breast')),
            ('both breasts', _('Both breasts')),
        ],
        max_length=255,
        verbose_name=_('Method')
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_('Amount'))
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-start']
        verbose_name = _('Feeding')
        verbose_name_plural = _('Feedings')

    def __str__(self):
        return str(_('Feeding'))

    def save(self, *args, **kwargs):
        if self.start and self.end:
            self.duration = self.end - self.start
        super(Feeding, self).save(*args, **kwargs)

    def clean(self):
        validate_time(self.start, 'start')
        validate_time(self.end, 'end')
        validate_duration(self)
        validate_unique_period(Feeding.objects.filter(child=self.child), self)


class Note(models.Model):
    model_name = 'note'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='note',
        verbose_name=_('Child')
    )
    note = models.TextField(verbose_name=_('Note'))
    time = models.DateTimeField(auto_now=True, verbose_name=_('Time'))

    objects = models.Manager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-time']
        verbose_name = _('Note')
        verbose_name_plural = _('Notes')

    def __str__(self):
        return str(_('Note'))


class NapsManager(models.Manager):
    def get_queryset(self):
        qs = super(NapsManager, self).get_queryset()
        return qs.filter(id__in=[obj.id for obj in qs if obj.nap])


class Sleep(models.Model):
    model_name = 'sleep'
    child = models.ForeignKey(
        'Child',
        on_delete=models.CASCADE,
        related_name='sleep',
        verbose_name=_('Child')
    )
    start = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('Start time')
    )
    end = models.DateTimeField(
        blank=False,
        null=False,
        verbose_name=_('End time')
    )
    duration = models.DurationField(
        editable=False,
        null=True,
        verbose_name=_('Duration')
    )
    notes = models.TextField(blank=True, null=True, verbose_name=_('Notes'))

    objects = models.Manager()
    naps = NapsManager()

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')
        ordering = ['-start']
        verbose_name = _('Sleep')
        verbose_name_plural = _('Sleep')

    def __str__(self):
        return str(_('Sleep'))

    @property
    def nap(self):
        nap_start_min = timezone.datetime.strptime(
            settings.BABY_BUDDY['NAP_START_MIN'], '%H:%M').time()
        nap_start_max = timezone.datetime.strptime(
            settings.BABY_BUDDY['NAP_START_MAX'], '%H:%M').time()
        local_start_time = timezone.localtime(self.start).time()

dashboard/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView

from babybuddy.mixins import PermissionRequired403Mixin
from core.models import Child


class Dashboard(LoginRequiredMixin, TemplateView):
    # TODO: Use .card-deck in this template once BS4 is finalized.
    template_name = 'dashboard/dashboard.html'

    # Show the overall dashboard or a child dashboard if one Child instance.
    def get(self, request, *args, **kwargs):
        children = Child.objects.count()
        if children == 0:
            return HttpResponseRedirect(reverse('babybuddy:welcome'))
        elif children == 1:
            return HttpResponseRedirect(
                reverse(
                    'dashboard:dashboard-child',
                    args={Child.objects.first().slug}
                )
            )
        return super(Dashboard, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['objects'] = Child.objects.all() \
            .order_by('last_name', 'first_name', 'id')
        return context


class ChildDashboard(PermissionRequired403Mixin, DetailView):
    model = Child
    permission_required = ('core.view_child',)
    raise_exception = True
    template_name = 'dashboard/child.html'

dashboard/templates/cards/base.html
<div class="card card-dashboard card-{{ type }}">
    <div class="card-header">
        <i class="icon icon-{{ type }} pull-left" aria-hidden="true"></i>
        {% block header %}{% endblock %}
    </div>
    <div class="card-body">
        <span class="card-title"><strong>{% block title %}{% endblock %}</strong></span>
        <div class="card-text">{% block content %}{% endblock %}</div>
    </div>
    {% block listgroup %}{% endblock %}
</div>

dashboard/templates/cards/diaperchange_last.html
{% extends 'cards/base.html' %}
{% load i18n %}

{% block header %}{% trans "Last Diaper Change" %}{% endblock %}

{% block title %}
    {% if change %}
        {% blocktrans trimmed with time=change.time|timesince %}
            {{ time }} ago
        {% endblocktrans %}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if change %}{{ change.attributes|join:', ' }}{% endif %}
{% endblock %}

dashboard/templates/cards/diaperchange_types.html
{% extends 'cards/base.html' %}
{% load i18n %}

{% block header %}{% trans "Diaper Changes" %}{% endblock %}

{% block title %}
    {% if total == 0 %}
        {% trans "None" %}
    {% else %}
        {% trans "Past Week" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% for key, info in stats.items %}
        {% if info.wet > 0 or info.solid > 0 %}
            <div class="progress mt-3">

                {% if info.wet_pct > 0 %}
                    <div class="progress-bar bg-primary lead"
                         role="progressbar"
                         style="width: {{ info.wet_pct|safe }}%;">{{ info.wet|floatformat:'0' }}&nbsp;{% trans "wet" %}</div>
                {% endif %}

                {% if info.solid_pct > 0 %}
                    <div class="progress-bar bg-secondary lead"
                         role="progressbar"
                         style="width: {{ info.solid_pct|safe }}%;">
                        {{ info.solid|floatformat:'0' }}&nbsp;{% trans "solid" %}</div>
                {% endif %}
            </div>
            <div class="text-center text-light small">
                {% if key == 0  %}
                    {% trans "today" %}
                {% elif key == 1 %}
                    {% trans "yesterday" %}
                {% else %}
                    {% blocktrans %}{{ key }} days ago{% endblocktrans %}
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

dashboard/templates/cards/feeding_last.html
{% extends 'cards/base.html' %}
{% load i18n %}

{% block header %}{% trans "Last Feeding" %}{% endblock %}

{% block title %}
    {% if feeding %}
        {% blocktrans trimmed with time=feeding.start|timesince %}
            {{ time }} ago
        {% endblocktrans %}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if feeding %}
        {{ feeding.get_type_display }}, {{ feeding.get_method_display }}
        {% if feeding.amount %}
            ({{ feeding.amount }})
        {% endif %}
    {% endif %}
{% endblock %}

dashboard/templates/cards/feeding_last_method.html
{% extends 'cards/base.html' %}
{% load i18n %}

{% block header %}{% trans "Last Feeding Method" %}{% endblock %}

{% block title %}
    {% if feedings|length > 0 %}
        <div id="feeding-methods-carousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
            {% for feeding in feedings %}
                <div class="carousel-item{% if forloop.counter == feedings|length %} active{% endif %}">
                    <div class="last-feeding-method text-center">{{ feeding.get_method_display }}</div>
                    <div class="text-center small text-muted">
                        {% if forloop.last %}
                            {% trans "most recent" %}
                        {% else %}
                            {% blocktrans trimmed with n=forloop.revcounter0 plural=forloop.revcounter0|pluralize %}
                                {{ n }} feeding{{ plural }} ago
                            {% endblocktrans %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
            {% if feedings|length > 1 %}
                <a class="carousel-control-prev" href="#feeding-methods-carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">{% trans "Previous" %}</span>
                </a>
                <a class="carousel-control-next" href="#feeding-methods-carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">{% trans "Next" %}</span>
                </a>
            {% endif %}
        </div>
    {% else %}
        {% trans "None" %}
    {% endif %}

{% endblock %}

dashboard/templates/cards/sleep_day.html
{% extends 'cards/base.html' %}
{% load duration i18n %}

{% block header %}{% trans "Today's Sleep" %}{% endblock %}

{% block title %}
    {% if total %}
        {{ total|duration_string }}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if count > 0 %}
        {% blocktrans %}{{ count }} sleep entries{% endblocktrans %}
    {% endif %}
{% endblock %}

dashboard/templates/cards/sleep_last.html
{% extends 'cards/base.html' %}
{% load duration i18n %}

{% block header %}{% trans "Last Sleep" %}{% endblock %}

{% block title %}
    {% if sleep %}
        {% blocktrans trimmed with time=sleep.end|timesince %}
            {{ time }} ago
        {% endblocktrans %}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block content %}{{ sleep.duration|duration_string }}{% endblock %}

dashboard/templates/cards/sleep_naps_day.html
{% extends 'cards/base.html' %}
{% load duration i18n %}

{% block header %}{% trans "Today's Naps" %}{% endblock %}

{% block title %}
    {% if count %}
        {% blocktrans trimmed with plural=count|pluralize %}
            {{ count }} nap{{ plural }}
        {% endblocktrans %}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if total %}{{ total|duration_string }}{% endif %}
{% endblock %}

dashboard/templates/cards/statistics.html
{% load duration i18n %}

<div class="card card-dashboard card-statistics">
    <div class="card-header">
         <i class="icon icon-graph pull-left" aria-hidden="true"></i>
        {% trans "Statistics" %}
    </div>
    <div class="card-body text-center">
        <div id="statistics-carousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
                {% for stat in stats %}
                    <div class="carousel-item{% if forloop.counter == 1 %} active{% endif %}">
                        <span class="card-title">
                            {% if stat.stat %}
                                {% if stat.type == 'duration' %}
                                    {{ stat.stat|duration_string:'m' }}
                                {% elif stat.type == 'float' %}
                                    {{ stat.stat|floatformat }}
                                {% else %}
                                    {{ stat.stat }}
                                {% endif %}
                            {% else %}
                                <em>{% trans "Not enough data" %}</em>
                            {% endif %}
                        </span>
                        <div class="card-text">{{ stat.title }}</div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#statistics-carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Previous" %}</span>
            </a>
            <a class="carousel-control-next" href="#statistics-carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">{% trans "Next" %}</span>
            </a>
        </div>
    </div>
</div>

dashboard/templates/cards/timer_list.html
{% extends 'cards/base.html' %}
{% load i18n %}

{% block header %}{% trans "Active Timers" %}{% endblock %}

{% block title %}
    {% with instances|length as count %}
        {% blocktrans trimmed with plural=count|pluralize %}
            {{ count }} active timer{{ plural }}
        {% endblocktrans %}
    {% endwith %}
{% endblock %}

{% block listgroup %}
    <ul class="list-group list-group-flush">
    {% for timer in instances %}
        <a href="{% url 'core:timer-detail' timer.id %}"
           class="list-group-item list-group-item-action">
            <strong>{{ timer.title_with_child }}</strong>
            <p class="text-muted small m-0">
                {% blocktrans trimmed with start=timer.start|time user=timer.user_username %}
                    Started by {{ user }} at {{ start }}
                {% endblocktrans %}
            </p>
        </a>
    {% endfor %}
    </ul>
{% endblock %}

dashboard/templates/cards/tummytime_day.html
{% extends 'cards/base.html' %}
{% load duration i18n %}

{% block header %}{% trans "Today's Tummy Time" %}{% endblock %}

{% block title %}
    {% if stats.count > 0 %}
        {{ stats.total|duration_string }}
    {% else %}
        {% trans "None" %}
    {% endif %}
{% endblock %}

{% block listgroup %}
    <ul class="list-group list-group-flush text-muted small">
    {% for instance in instances %}
        <li class="list-group-item">
            {% blocktrans trimmed with duration=instance.duration|duration_string end=instance.end|time %}
                {{ duration }} at {{ end }}
            {% endblocktrans %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

dashboard/templates/cards/tummytime_last.html
{% extends 'cards/base.html' %}
{% load duration i18n %}

{% block header %}{% trans "Last Tummy Time" %}{% endblock %}

{% block title %}
    {% if tummytime %}
        {% blocktrans trimmed with time=tummytime.time|timesince %}
            {{ time }} ago
        {% endblocktrans %}
    {% else %}
        {% trans "Never" %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if tummytime %}
        {{ tummytime.duration|duration_string }}
        {% if tummytime.milestone %}
            <br /> {{ tummytime.milestone }}
        {% endif %}
    {% endif %}
{% endblock %}